name: Deploy book on GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: rust-cargo-install
        uses: actions-rs/install@v0.1.2
        with:
          crate: mdbook
          version: ^0.3
          use-tool-cache: true
          use-cache: true
      - name: Build by mdbook
        run: mdbook build ./

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: book

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          publish_dir: ./artifact
          publish_branch: gh-pages
